baseURL                         = "https://www.4l3c.org/"   # Your domain name. Must end with "/"
languageCode                    = "it"
defaultContentLanguage          = "it"                    # Default language for multilingual sites
theme                           = "4l3c-hugo-theme"
title                           = "4l3c"

sectionPagesMenu                = "main"

disqusshortname                 = "4l3cdotorg"
googleAnalytics                 = "UA-18092151-1"
enableRobotsTXT                 = "true"
enableGitInfo                   = "true"

[permalinks]
  posts                         = "/:year/:month/:title/"

[sitemap]
  changefreq                    = "monthly"
  priority                      = 0.5
  filename                      = "sitemap.xml"

[params]
  Author                      = "Alessandro Bernardi"
  description                 = "4l3c a.k.a. Alessandro Bernardi - blog"
  subtitle                    = "a.k.a. Alessandro Bernardi"
  # mainSections                = ["posts", "tutorial"]
  mainSections                = ["posts"]
  # favicon                     = ""
  # site_logo                   = ""
  facebook                    = "https://www.facebook.com/alessandro.bernardi"
  twitter                     = "https://twitter.com/alexberny"
  # instagram                  = ""
  youtube                     = "https://www.youtube.com/c/AlessandroBernardi-4l3c"
  github                      = "https://github.com/alexberny"
  # gitlab                     = ""
  linkedin                    = "https://www.linkedin.com/in/alessandro-bernardi-103bc1b"
  mastodon                    = "https://mastodon.uno/@4l3c"
  # slack = ""
  # stackoverflow = ""
  # rss = ""
  meta_description            = "Blog personale di 4l3c a.k.a. Alessandro Bernardi"
  ibenda_cookiePolicyId       = "13294331"
  iubenda_siteId              = "2107002"
  sourcecode_repo             = "https://github.com/alexberny/4l3c-blog"

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

  [languages]
    [languages.it]

# [params]
#     themeStyle                   = "dark"                 # Choose "light" or "dark"
#     favicon                      = "/img/fav.ico"          # Path to favicon file
#     showRSSButton                = false                   # Show rss button in navigation
#     fadeIn                       = false                    # Turn on/off the fade-in effect
#     fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
#     dateFormat                   = "Jan 2, 2006"
#     email                        = "alexberny@yahoo.it"   # E-mail address for contact section
#     # customCSS                  = ["foo.css"]             # Include custom css files placed under assets/
#     # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/

#     # Configure the home page
#     [params.home]
#         introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
#         showLatest               = true                    # Show latest blog post summary
#         showAllPosts             = true                   # Set true to list all posts on home page, or set false to link to separate blog list page
#         numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
#         localTime                = true                    # Show your current local time in contact section
#         timeZone                 = "Europe/Rome"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#         timeFormat               = "H:mm"
#         useTwoColumns            = false                   # Use a layout with two columns instead of three

#     # Share buttons on blog post pages
#     [params.share]
#         twitter                  = true
#         facebook                 = true
#         googlePlus               = true
#         pinterest                = true

#     # Social icons appear in introduction and contact section. Add as many more as you like.
#     # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
#     # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
#     [[params.social]]
#         url   = "https://twitter.com/"
#         icon  = "twitter" # icon name without the 'fa-'
#         icon_pack = "fab"
#     [[params.social]]
#         url   = "https://facebook.com/"
#         icon  = "facebook-f" # icon name without the 'fa-'
#         icon_pack = "fab"
#     [[params.social]]
#         url   = "https://linkedin.com/"
#         icon  = "linkedin-in" # icon name without the 'fa-'
#         icon_pack = "fab"
#     [[params.social]]
#         url = "mailto:youremail@email.com"  # For a direct email link, use "mailto:test@example.org".
#         icon = "paper-plane" # icon name without the 'fa-'
#         icon_pack = "fas"
#     [[params.social]]
#         url   = "https://mastodon.social/"
#         icon  = "mastodon" # icon name without the 'fa-'
#         icon_pack = "fab"
#         html_attributes = "rel=\"me\"" # Add rel attribute for Mastodon profile link verification


# # If you don't want to use the default menu, you can define one by yourself
# # [[menu.main]]
# #     name    = "Home"
# #     url     = "/"
# #     weight  = 0
# # [[menu.main]]
# #     name    = "Blog"
# #     url     = "/blog/"
# #     weight  = 1

# # We only use tag as a taxonomies
# # You can add more by yourself
# [taxonomies]
#   tag = "tags"
#   series = "series"

# [markup]
#   defaultMarkdownHandler = "goldmark"
#   [markup.goldmark]
#   [markup.goldmark.renderer]
#     unsafe = true
#   [markup.highlight]
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = true
#     # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
#     style = "friendly"
#     tabWidth = 4

# # [languages]
# #     [languages.en]
# #         languageName     = "English"
# #         languageCode     = "en-us"
# #         contentDir       = "content/en"
# #         weight           = 0
# #         title            = "Introduction"
# #         [languages.en.params]
# #             description  = "Website Description"   # Max 160 characters show in search results
# #             # footerText   = ""                      # Text to override default footer text (markdown allowed)

# #     [languages.es]
# #         languageName     = "Español"
# #         languageCode     = "es"
# #         contentDir       = "content/es"
# #         weight           = 1
# #         title            = "Introducción"
# #         [languages.es.params]
# #             description  = "Descripcion del sitio web"
# #             # footerText   = ""

# #     [languages.de]
# #         languageName     = "Deutsch"
# #         languageCode     = "de"
# #         contentDir       = "content/de"
# #         weight           = 2
# #         title            = "Vorstellung"
# #         [languages.de.params]
# #             dateFormat   = "2. January 2006"
# #             description  = "Beschreibung der Webseite"
# #             # footerText   = ""

# #     [languages.it]
# #         languageName     = "Deutsch"
# #         languageCode     = "it"
# #         contentDir       = "content/it"
# #         weight           = 3
# #         title            = "Introduzione"
# #         [languages.it.params]
# #             dateFormat   = "2 January 2006"
# #             description  = "Descrizione del sito"
# #             # footerText   = ""
